### ISSUE TITLE
Error: Port 5173 is already in use

### ISSUE THREAD

**Issue by Gijela** [TinsFox/shadcnui-boilerplate#18]
Following the `getting-started.md` guide, after I completed the `pnpm i` command, running `pnpm run dev` consistently throws the error `Error: Port 5173 is already in use`. I tried executing `lsof -ti :5173 | xargs kill` to terminate the port, but after rerunning `pnpm run dev`, the same issue persists.

![image](https://github.com/user-attachments/assets/b0173058-589c-463b-81b7-f92aeb7f41db)

**Comment by TinsFox** [comment]
I'm sorry about this. There are still some problems with the script here and it has not been fully tested. If you want to run the background, you can use the command `pnpm run admin:dev`

But you need to configure the API address first. This may be helpful to you.

https://github.com/TinsFox/shadcnui-boilerplate/issues/16#issuecomment-2487687089

Thanks for the report, I think I know where the problem is and I will fix it as soon as possible.

**Comment by Gijela** [comment]
> I'm sorry about this. There are still some problems with the script here and it has not been fully tested. If you want to run the background, you can use the command `pnpm run admin:dev`
> 
> But you need to configure the API address first. This may be helpful to you.
> 
> [#16 (comment)](https://github.com/TinsFox/shadcnui-boilerplate/issues/16#issuecomment-2487687089)
> 
> Thanks for the report, I think I know where the problem is and I will fix it as soon as possible.

fixed. 
thanks
